name: Run longtail tests

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        conf: [Release, Debug]
        target: [net5.0, net6.0, net7.0, net9.0]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.conf }} - ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v2

    - name: Install .NET 5, 6, 7 and 9
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x
          9.0.x
        include-prerelease: true

    - name: Build
      run: dotnet build src/Longtail -c ${{ matrix.conf }} -f ${{ matrix.target }}

    - name: Test
      if: matrix.target == 'net9.0'
      run: dotnet test tests/Longtail.Tests -c ${{ matrix.conf }} -f ${{ matrix.target }}

  package:
    needs: build
    runs-on: ubuntu-latest
    name: Nuget package
    steps:
    - uses: actions/checkout@v2

    - name: Install .NET 5, 6, 7 and 9
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x
          9.0.x
        include-prerelease: true

    - name: Package
      run: dotnet pack src/Longtail -c Release -o release/

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: release/*.nupkg
