name: Run longtail tests

on: push

jobs:
  build:
    strategy:  
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        conf: [Release, Debug]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.conf }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Install .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
        
    - name: Build
      run: dotnet build src/Longtail -c ${{ matrix.conf }}
    
    - name: Test
      run: dotnet test tests/Longtail.Tests -c ${{ matrix.conf }}
